# https://kubernetes.io/docs/concepts/workloads/controllers/deployment/
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spotify-release-radar
  namespace: default
  labels:
    app: spotify-release-radar
spec:
  selector:
    matchLabels:
      app: spotify-release-radar
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: spotify-release-radar
    spec:
      containers:
      - name: spotify-release-radar
        image: spotify-release-radar:latest
        ports:
        - containerPort: 8080
          name: http

